#!/bin/bash

fs=""
size=""
usedspace=""
elapsed="00:00:00"
remaining="00:00:00"
percent=0
bitrate=0

# Strip comma and percent
stripcomma="sed s/[,%]//g"

cat /dev/stdin| _r_to_n |while read line; do
  [ -z "$line" ] && continue
  echo $line|grep 'File system'>/dev/null && fs=$(echo $line|sed 's/File system://'  | sed -e 's/^ *//' -e 's/ *$//')
  echo $line|grep 'Device size'>/dev/null && size=$(echo $line|sed 's/Device size://'  | sed -e 's/^ *//' -e 's/ *$//')
  echo $line|grep 'Space in use'>/dev/null && usedspace=$(echo $line|sed 's/Space in use://'  | sed -e 's/^ *//' -e 's/ *$//')
  
  if echo $line|grep 'Completed:'>/dev/null; then
    elapsed=$(echo $line|awk '{ print $2 }'| $stripcomma )
    remaining=$(echo $line|awk '{ print $4 }'| $stripcomma )
    percent=$(echo $line|awk '{ print $6 }'| $stripcomma )
    # decimal point not supoprted by dialog
    percent=$(echo $percent|tr '.' ' '|awk '{print $1}')
    bitrate=$(echo $line|awk '{ print $7 }'| $stripcomma )
  fi

# Show current progress
cat <<EOF
XXX
$percent
 
Restauration de machin truc
Système de fichier: $fs
Espace utilisé: $usedspace

Temps écoulé: $elapsed
Temps restant: $remaining

Débit: $bitrate
XXX
EOF

done |
dialog --backtitle "Pulse imaging client" --title "Mandriva Pulse: $1" --gauge "Please wait" 15 70 0
exit 0
